@url=http://127.0.0.1:3333/api

###

# Find all players #
GET {{url}}/players
###
# Get player by id #
GET {{url}}/players/1
# Delete player by id #
DELETE {{url}}/players/1
###
# Create player #
POST  {{url}}/players
Content-Type: application/json

{
  "name": "Bob",
  "club": "futebol Clube",
  "nationality": "Brasil",
  "position": "Atacante",
  "statistics": { 
    "Overall": 99,
    "Pace": 79,
    "Shooting": 60,
    "Passing": 35,
    "Dribbling": 60,
    "Defending": 56,
    "Physical": 72
  }
}
###
# Update Player
PATCH   {{url}}/players/16
Content-Type: application/json

{
    "Overall": 919,
    "Pace": 79,
    "Shooting": 60,
    "Passing": 35,
    "Dribbling": 60,
    "Defending": 56,
    "Physical": 72
}
###
